### ISSUE TITLE
Save and Load the Handpose model to avoid memory leaks

### ISSUE THREAD

**Issue by rakia** [mgechev/angular-tfjs-demo#2]
Hi @mgechev, 
Thanks for this inspiring example! I have a dynamic stepper implemented as an Angular library and it has the navigation between steps with hand tracking as a feature in it (I have used your same source code with a slight modification in order to be able to go to the next/previous step instead of open/close an item in the menu).

DynamicStepperModule is used in order-creation and product-details views and is the one that is responsible for loading and releasing the hand pose model (via the HandGestureService) and not the main app (AppComponent) as in your example.

To avoid loading the model whenever the user visits the details view (which caused memory leaks in my project: https://betterprogramming.pub/web-performance-and-tensorflow-js-3db05b1de958), I need to save the model after its first load in localStorage, then load it from there. But I haven't found yet the best solution to do this. I've tried the following in HandGestureService (after adding 'json-cyclic' library to solve the serialization of the model that has cyclic references) but got "**RangeError: Maximum call stack size exceeded**":

`import { encycle, decycle } from 'json-cyclic';
const modelFromLocalStorage = localStorage.getItem('handPoseModel');
        if (!modelFromLocalStorage) {
          const handPoseModel = await handpose.load();
          localStorage.setItem('handPoseModel', JSON.stringify(encycle(handPoseModel)));
          return handPoseModel;
        }`

It would be great if you could add saving/loading the Handpose model in/from localStorage to this project.

My app is available online here: https://angular-dynamic-stepper-4a371.web.app
The source code is on GitHub here: https://github.com/rakia/ng-dynamic-stepper

Many thanks!
Rakia

**Comment by mgechev** [comment]
Hey Rakia, you can look into loading the model in a service. If it has `providedIn: 'root'` then it'll likely be a singleton and you'd load the model only once.

**Comment by rakia** [comment]
The problem is not with multiple instances of HandGestureService (I have only one instance when add providedIn: 'root'), but it's rather with the call to the `initialize()` method which is called each time the user visits the details-page:

`ngAfterViewInit(): void {
    this.handGestureService.initialize(this.canvas.nativeElement, this.video.nativeElement);
  }`

`<lib-dynamic-stepper [steps]=“steps”
[currentStep]=“currentStep”
[showGoBack]=“true”
(goBack)=“goBack()”
(gotoStep)=“onGotoStep($event)”
(gotoNextStep)=“gotoNextStep()”
(gotoPreviousStep)=“gotoPreviousStep()”>`

I have changed the `initialize()` method in HandGestureService as follow but got an error:

`if (!this._handPoseModel) {
          this._handPoseModel = await handpose.load();
        }
          return this._handPoseModel;`

Error: Uncaught (in promise): Error: The video element has not loaded data yet. Please wait for `loadeddata` event on the <video> element.
Error: The video element has not loaded data yet. Please wait for `loadeddata` event on the <video> element.

**Comment by rakia** [comment]
Memory Leaks Fixed :) after saving the handPose model in a variable (_handPoseModel: HandPose) in HandGestureService and wrapping model.estimateHands(video).then(..) in video.addEventListener('loadeddata', (e) => {..})

The solution is available here: https://github.com/rakia/ng-dynamic-stepper/blob/master/projects/dynamic-stepper/src/lib/ml/hand-gesture.service.ts

and [an article about it is available here](https://levelup.gitconnected.com/how-to-use-tensorflow-js-without-memory-leaks-273ad16196be).

**Comment by rakia** [comment]
Hey Minko,
what do you think about adjusting hand-gesture.service.ts as I've done in this gist (the difference is in lines 53 - 63):
https://gist.github.com/rakia/870517cf4e6c059881d6a364176c2188

I couldn't create a pull request for it because I don't have access to create a new branch here.

**Comment by mgechev** [comment]
@rakia, you can fork the repository and open a PR via your fork.
